import { StyleSheet } from 'react-native';
import { Platform } from 'react-native';
import { Colors } from '../../constants/Theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9F9F9',
  },
  btn_yellow: {
    backgroundColor: '#EAEAEA',
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    borderRadius: 8,
    marginBottom: Platform.OS === 'ios' ? 25 : 15,
    alignSelf: 'center',
  },
  heading1: {
    marginTop: 20,
    marginBottom: 21,
    fontSize: 20,
    color: 'black',
    textAlign: 'center',
    fontFamily: 'ProximaNovaBold',
  },
  main_container: {
    marginHorizontal: 10,
    flex: 8,
    alignItems: 'center',
  },
  inputsTopTow: {
    borderColor: '#E3E3E3',
    borderWidth: 1,
    width: 270,
    paddingLeft: 10,
    paddingRight: 10,
    height: 48,
    borderRadius: 10,
    backgroundColor: '#fff',
    fontFamily: 'ProximaNova',
    fontSize: 16,
  },
  inputLabel: {
    color: 'black',
    opacity: 0.8,
    paddingBottom: 2.7,
    fontSize: 16,
    fontFamily: 'ProximaNovaBold',
  },
  input_box: {
    marginBottom: 16,
  },
  smallInput: {
    width: 48,
    height: 48,
    paddingLeft: 18,
    borderColor: '#E3E3E3',
    borderWidth: 1,
    borderRadius: 10,
    fontSize: 16,
    backgroundColor: 'white',
  },
  waiterInput: {
    borderColor: '#ccc',
    borderWidth: 1,
    width: 140,
    padding: 10,
    fontSize: 16,
    borderRadius: 10,
    backgroundColor: '#fff',
    fontFamily: 'ProximaNova',
    height: 48,
  },
  chooseButtons_container: {
    width: 270,
    flexDirection: 'row',
    backgroundColor: '#fff',
    justifyContent: 'center',
    height: 48,
    borderColor: '#E3E3E3',
    borderWidth: 1,
    borderRadius: 7,
  },
  time_opt: {
    width: 135,
    height: 47,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#E3E3E3',
  },
  timeTxt: {
    fontFamily: 'ProximaNova',
    fontSize: 16,
  },
  experience: {
    paddingLeft: 12,
    paddingTop: 14,
    fontFamily: 'ProximaNova',
    fontSize: 15,
    fontWeight: '600',
  },
  AutocompleteStyle: {
    flex: 1,
    left: 0,
    // position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 1,
    borderWidth: 1,
  },
  expBox: {
    backgroundColor: '#fff',
    borderColor: '#E3E3E3',
    borderWidth: 1,
    borderRadius: 13,
    paddingVertical: 15,
    paddingHorizontal: 15,
    marginTop: 10,
    paddingBottom: 22,
  },
  expTxt1: {
    fontFamily: 'ProximaNovaBold',
    fontSize: 14,
  },
  expTxt2: {
    fontFamily: 'ProximaNova',
    fontSize: 14,
    paddingVertical: 10,
  },
  expTxt3: {
    fontFamily: 'ProximaNova',
    fontSize: 14,
  },
  viewAddReview: {
    width: '110%',
    alignSelf: 'center',
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    paddingVertical: 10,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#DADADA',
    // height:40,
    marginTop: 30,
  },
  btnAdd: {
    backgroundColor: Colors.yellow,
    padding: 4,
    borderRadius: 6,
    marginLeft: 10,
  },
  txtAddReview: {
    fontSize: 16,
    color: Colors.fontDark,
  },
  availabilityCard: {
    backgroundColor: '#fff',
    borderColor: '#E3E3E3',
    borderWidth: 1,
    borderRadius: 13,
    marginTop: 10,
    // paddingHorizontal:-10,
    paddingVertical: 15,
    paddingHorizontal: 15,
    flexDirection: 'row',
    maxWidth: 290,
  },
  availTxt1: {
    fontFamily: 'ProximaNovaBold',
    fontSize: 14,
  },
  availTxt2: {
    marginLeft: 20,
    fontFamily: 'ProximaNova',
    fontSize: 14,
  },
  //Restaurant textbox
  input_icon: {
    flexDirection: 'row',
    borderColor: '#E3E3E3',
    borderWidth: 1,
    width: 270,
    paddingLeft: 10,
    paddingRight: 10,
    height: 48,
    borderRadius: 10,
    backgroundColor: '#fff',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  input_icon_text: {
    fontSize: 15,
    width: 225,
    textAlign: 'center',
  },
  options: {
    maxHeight: 150,
    backgroundColor: '#f0f0f0',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    marginLeft: 7,
    marginRight: 7,
  },
  opt_txt: {
    fontSize: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    padding: 10,
    fontFamily: 'ProximaNova',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
});

export default styles;
