export const USER_DETAILS = 'USER_DETAILS';
export const RESTAURANTS_DETAILS = 'RESTAURANTS_DETAILS';
export const YOUR_RESTAURANTS = 'YOUR_RESTAURANTS';
export const REFRESH_ANIMATION = 'REFRESH_ANIMATION';